name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2


      - name: Security scan with Bandit
        run: |
          pip install bandit
          # Only fail on high severity, high confidence issues
          bandit -r . \
            --severity-level high \
            --confidence-level high \
        continue-on-error: true  # Review findings but don't block build immediately
        

      - name: Scan Python dependencies
        run: |
          pip install pip-audit
          pip-audit || echo "Vulnerabilities found - continuing for now"
        continue-on-error: true
                  

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run:  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-demo-app:${{ github.sha }} .

      - name: Install Trivy
        run: |
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.68.1

      - name: Scan Docker image
        run: trivy image --exit-code 1 --severity HIGH, CRITICAL ${{ secrets.DOCKERHUB_USERNAME }}/my-demo-app:${{ github.sha }}

      - name: Tag image as latest
        run: |
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-demo-app:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-demo-app:latest

    
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-demo-app:latest

